### PR TITLE
Change section headings and some css tweaks

### LINKED ISSUE #3: Design is not  mobile responsive

### LINKED ISSUE #4: Same section heading
Profile is repeated

### PR DESCRIPTION
**Pull request by AnkushMalik**
Change section heading and description
Remove horizontal scroll on animation and sections visible on mobile view for the time being
Closes #3, #4

### CODE REVIEW

**Comment by AnkushMalik** [comment]
commit command was like : 

```
git commit -m "Change section headings" -m "
Change section heading and description
Closes #4"
```

Commit like above for better development (issue will be closed by the last line of commit ^ )

**Comment by mythrex** [comment]
Sure!

**Comment by mythrex** [comment]
But that scroll jerk issue was fixed in the latest commit.

**Comment by AnkushMalik** [comment]
I m not talking about y scroll I fixed x scroll jerk.

**Pull request merged**
